name: 'sales_prediction'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


  # marts_analytics:
  #   materialized: table
  #   +schema: marts_analytics
  #   +tags: conformed

models:
  +persist_docs:
    relation: true
    columns: true
  sales_prediction:
    staging:
      +materialized: view
      +schema: stg

  elementary:
    +schema: 'elementary'
      